//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestTable
    {
        public int id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string petdetails { get; set; }
        public string duration { get; set; }
        public string phone { get; set; }
        public string requestdetails { get; set; }
        public string amount { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
