//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfitTable
    {
        public int id { get; set; }
        public int customer_id { get; set; }
        public string name { get; set; }
        public System.DateTime date { get; set; }
        public string phone { get; set; }
        public decimal paid_amount { get; set; }
        public decimal given_amount { get; set; }
        public decimal other_cost { get; set; }
        public decimal total_cost { get; set; }
        public decimal profit { get; set; }
    }
}
